### ISSUE TITLE
Recorrecting the town name

### ISSUE THREAD

**Issue by haritianaadriano** [fenohei/SOAVADIA#3]
Hello, i recently washed the insert.sql file and i want to ask a comment with this, in my fork and i'had resolved the problem. The problem in question is the town name, because in the prod branch the town name was not a town name of Madagascar and i want to show you that. SOAVADIA/insert/insert.sql => change town_name nom_ville => nom_ville_madagascar @fenohei #2

**Comment by fenohei** [comment]
Hello, i will fix this

**Comment by haritianaadriano** [comment]
> Hello, i recently washed the insert.sql file and i want to ask a comment with this, in my fork and i'had resolved the problem. The problem in question is the town name, because in the prod branch the town name was not a town name of Madagascar and i want to show you that. SOAVADIA/insert/insert.sql => change town_name nom_ville => nom_ville_madagascar @fenohei #2
